spring:
  datasource:
    url: jdbc:postgresql://postgres-q6vt.railway.internal:5432/railway
    username: postgres
    password: fPbRTpewhNFxhTRlctEJitzLOkxqoqiz
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-path
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8080
  address: 0.0.0.0

frontend:
  url: https://govlearn-client-production.up.railway.app

backend:
  url: https://govlearn-production.up.railway.app